/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNITest */

#ifndef _Included_JNITest
#define _Included_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNITest
 * Method:    jniMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNITest_jniMethod
  (JNIEnv *, jclass);

/*
 * Class:     JNITest
 * Method:    staticJniMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNITest_staticJniMethod
  (JNIEnv *, jclass);

/*
 * Class:     JNITest
 * Method:    setIn0
 * Signature: (Ljava/io/InputStream;Ljava/io/InputStream;Ljava/io/InputStream;Ljava/io/InputStream;Ljava/io/InputStream;Ljava/io/InputStream;Ljava/io/InputStream;Ljava/io/InputStream;Ljava/io/InputStream;Ljava/io/InputStream;Ljava/io/InputStream;Ljava/io/InputStream;Ljava/io/InputStream;Ljava/io/InputStream;Ljava/io/InputStream;Ljava/io/InputStream;Ljava/io/InputStream;Ljava/io/InputStream;)V
 */
JNIEXPORT void JNICALL Java_JNITest_setIn0
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
